"""
Contact Form Schemas
─────────────────────
Pydantic models that describe the shape of contact form data.

Two models here:
- ContactCreate  → what the frontend SENDS (input from user)
- ContactResponse → what the API RETURNS (response sent back)

Why split into two models?
- Input doesn't have an id or timestamp (those are generated by the server)
- Output should include id + timestamp for the frontend's confirmation
- Different shapes = different models, clean and explicit
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, EmailStr, Field


class ContactCreate(BaseModel):
    """
    Shape of incoming contact form submissions.
    Used to validate POST /api/contact request body.
    """
    name: str = Field(..., min_length=2, max_length=100, description="Sender's name")
    email: EmailStr = Field(..., description="Sender's email address")
    subject: Optional[str] = Field(None, max_length=200, description="Optional subject line")
    message: str = Field(..., min_length=10, max_length=2000, description="The message content")

    # Example data shown in Swagger UI
    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "Jane Doe",
                "email": "jane@example.com",
                "subject": "Collaboration opportunity",
                "message": "Hi Marni, I'd love to discuss a project idea with you.",
            }
        }
    }


class ContactResponse(BaseModel):
    """
    Shape of the response sent back after a successful submission.
    Confirms to the frontend that the message was received.
    """
    success: bool
    message: str
    id: str
    created_at: datetime